### PR TITLE
Milestone 2 : Version 0.1.0

### PR DESCRIPTION
**Pull request by simandebvu**
## Release 0.1.0

In this milestone I have 

- Resolved Stickler issues 
- Added necessary HTML and CSS to clone the Apple 2014 Site

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
# Changes Required!
Hi @simandebvu, great job with this project so far! :+1:  You, however, have some more requirements to implement to have this project approved.
# Required:
- [x] For the main background, the CSS background should `cover` the whole page irrespective of the screen size. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/building_with_backgrounds_and_gradients/background_size_requirement.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538830/)). Please position your background image appropriately.
- [x] The four bottom elements should be links.
- [x] Size and position your elements more appropriately to make your clone look more like the original site. There is unnecessary white space after the footer on your clone.

__Kindly work on the above changes and submit another code review request__
_Feel free to contact me on slack for any inquiries about this review_ :wink: 
__Treasure Kabareebe__

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi @simandebvu 👋

You have done quite well in this project however kindly fix these:

- [x] - Ensure that the bottom images fit into the page width, as seen on the original webpage. They seem to be overflowing the page width as set by the top large background image.
[Screenshot]👇
ice_screenshot_20200511-145212

- [x] Also kindly increase the font size of these text elements to make them look like the original webpage.
[Screenshot] 
ice_screenshot_20200511-145237

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by simandebvu** [comment]
Changes made:

- Thumbnail links overflow on larger screens fixed
- Adjusted header font size

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — APPROVED** [review]
## Status: Approved :trophy: :airplane: 

Hi @simandebvu, congratulations for this great effort and project :smile: Thanks to your hard work and dedication and the hard work of the TSE's, the project now meets all the minimum requirements :smile: 
Bravo :+1: You can go ahead and merge to master, do not forget to submit the project completion form

Good luck with your next projects
_Happy coding_ :man_technologist: 
Daniel Larbi Addo in slack

**Pull request merged**
